---
# This playbook will just download new version of Jetty and install/extract it, then create a syslink for it so that the OS will use this new version
# i.e. An older version of Jetty should have been installed before
# The user, group, etc. config should have been set before
# External script is needed to deploy (by using start.jar)

- name: Download distribution tarball
  get_url:
    url="https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/{{ jetty_version }}/jetty-distribution-{{ jetty_version }}.tar.gz"
    dest={{ jetty_src_dir }}

- name: Unpack distribution
  shell: "tar zxf {{ jetty_src_dir }}/jetty-distribution-{{ jetty_version }}.tar.gz"
  args:
    chdir: "{{ jetty_dst_dir }}"
    creates: "{{ jetty_dst_dir}}/jetty-distribution-{{ jetty_version }}"

- name: Create symbolic link to distribution
  file:
    src="{{ jetty_dst_dir }}/jetty-distribution-{{ jetty_version}}"
    dest={{ jetty_dst_dir }}/jetty
    state=link
